### ISSUE TITLE
Definition of: Currently this project is in a complete rewrite

### ISSUE THREAD

**Issue by aryaminus** [rishadbaniya/hyperblow#13]
Awesome client bud!

Can you drop your plan of refactoring/rewriting? I was about to cherry pick hyperblow within a project in tauri. But wanted to ask before I went deep waters

**Comment by rishadbaniya** [comment]
It means, previously it had a complete BitTorrent V1 protocol implemented(with few algorithms missing for efficient download), but i stripped out almost all the code, because of how ugly it was and the conventions i followed before. Now i'm rewriting it with a goal of better documentations, good conventions and a better looking TUI. It's still far from being called complete, but i do have a goal of making it efficiently workable in 2 months

**Comment by rishadbaniya** [comment]
I'm sorry to say, but it's not usable as of this moment

**Comment by aryaminus** [comment]
Noted. Thanks bud. Will be keeping my eye on hyberblow, else I'll just have to get my hands dirty 🫡
